### ISSUE TITLE
Does not run...

### ISSUE THREAD

**Issue by Rigel772** [lestex/udemydl#2]
Hi there, when I try to run it, after entering email and password I am getting this error:
```
 udemydl https://www.udemy.com/XXXXXXXXXX --debug
Username / Email : XXXXXXX
Password: 
Traceback (most recent call last):
  File "/home/oskar/.local/bin/udemydl", line 8, in <module>
    sys.exit(main())
  File "/home/oskar/.local/lib/python3.8/site-packages/udemy_dl/__main__.py", line 4, in main
    cli().run()
  File "/home/oskar/.local/lib/python3.8/site-packages/udemy_dl/cli.py", line 58, in run
    sys_information = sys_info()
  File "/home/oskar/.local/lib/python3.8/site-packages/udemy_dl/utils.py", line 14, in sys_info
    linux_ver = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```
Any idea how to fix it? 
(I am on linux Manjaro Python 3.8.2)

**Comment by lestex** [comment]
Well it’s a change to a library in python 3.8, you can try and use 3.7

**Comment by lestex** [comment]
Has been fixed in https://github.com/lestex/udemydl/commit/144cca740a7057eac2eacd1e702da0b66422dd00.
Closing
