### ISSUE TITLE
'NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by betastt** [lestex/udemydl#4]
PS C:\Program Files\platzidl\udemydl> udemydl https://www.udemy.com/course/python3-programacion-orientada-a-objetos --debug
Username / Email : Email@gmail.com
Password:
DEBUG    Running on:
DEBUG    Python: CPython 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
DEBUG    Platform: Windows-10-10.0.183-SP0 [10.0.183]
DEBUG    OS: Windows - 10 10.0.183
DEBUG    Downloading course to: C:\Program Files\platzidl\udemydl\python3-programacion-orientada-a-objetos
DEBUG    Downloading with quality: 720
INFO     Trying to log in ...
ERROR    Unknown Exception
ERROR    'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\users\franc\appdata\local\programs\python\python37\lib\site-packages\udemy_dl\cli.py", line 77, in run
    with UdemyDownload(link, username, password, output_dir, quality) as ud:
  File "c:\users\franc\appdata\local\programs\python\python37\lib\site-packages\udemy_dl\udemy_download.py", line 21, in __enter__
    self.login()
  File "c:\users\franc\appdata\local\programs\python\python37\lib\site-packages\udemy_dl\udemy_download.py", line 34, in login
    csrf_token = self.__get_csrf_token()
  File "c:\users\franc\appdata\local\programs\python\python37\lib\site-packages\udemy_dl\udemy_download.py", line 30, in __get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I have pip, python3.7 and requests but I get an error

**Comment by lestex** [comment]
I'll fix it in the next release, supposed to be 0.6.1.

**Comment by lestex** [comment]
https://pypi.org/project/udemydl/
